name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        runs-on: ubuntu-latest
        steps:
            # https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v4.2.2
            # https://github.com/marketplace/actions/setup-go-environment
            - uses: actions/setup-go@v5.1.0
              with:
                  go-version: "1.23"
            # https://github.com/marketplace/actions/golangci-lint
            - uses: golangci/golangci-lint-action@v6.1.1
              with:
                  # https://github.com/golangci/golangci-lint/releases
                  version: v1.62.0
            - run: make build
