name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        runs-on: ubuntu-22.04
        steps:
            # https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v4.1.1
            # https://github.com/marketplace/actions/setup-go-environment
            - uses: actions/setup-go@v5.0.0
              with:
                  go-version: "1.22"
            # https://github.com/marketplace/actions/run-golangci-lint
            - uses: golangci/golangci-lint-action@v4.0.0
              with:
                  # https://github.com/golangci/golangci-lint/releases
                  version: v1.56.2
            - run: make build
